output_name = {9acddf6d-43cc-576e-9aff-0c5fc80b4cc8}
dd_configuration_option = ensure_active
dd_resolution_option = auto
dd_refresh_rate_option = auto
dd_hdr_option = disabled
dd_config_revert_delay = 3000
dd_config_revert_on_disconnect = enabled
dd_wa_hdr_toggle_delay = 500
